---
- apt:
    pkg: apt-transport-https

- apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

- apt_repository:
    repo: deb https://get.docker.com/ubuntu docker main
    update_cache: yes

- apt:
    pkg: lxc-docker
    state: latest
